### ISSUE TITLE
The demo.apk is broken.

### ISSUE THREAD

**Issue by twlkyao** [bugtags/Bugtags-Android-Eclipse#1]
The demo.apk is broken.

**Comment by kevinho** [comment]
Which demo.apk? I have no demo.apk in this project:https://github.com/bugtags/Bugtags-Android-Eclipse.
But I do have a demo.apk in https://github.com/bugtags/Bugtags-Android/blob/master/screenshot/demo.apk

**Comment by twlkyao** [comment]
Yeah, that's the link,https://github.com/bugtags/Bugtags-Android/blob/master/screenshot/demo.apk

**Comment by kevinho** [comment]
Hi, I open this link, click view raw, download is complete, and install is OK.
Is it the problem of GFW? Further question, please email me:he.changbin@bugtags.com or join our qq tribe: 102516533(if you know what it is).

**Comment by twlkyao** [comment]
My step was save link as, and I used Chrome, but I have solved this problem by downloading the whole project.

**Comment by kevinho** [comment]
hmm，i think something happens to the browser of network.
